language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
os:
  - linux
install:
  - travis_retry pip install tox
  - pip install codecov
script:
  - tox
after_success:
  - codecov
